seed_everything: 42
model:
  class_path: project.model.MyModel
  init_args:
    in_channels: 20
    hidden_channels: 32
    num_layers: 2
    heads: 2
    out_channels: 1
    dropout: 0.01
    jk: "last"
data:
  class_path: project.data.MyDataModule
  init_args:
    dataset_file: /dodrio/scratch/projects/2024_301/Deep-Learning-Protein-Structure-Prediction/data/hackathon_data/data.csv
    batch_size: 8
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.01
trainer:
  deterministic: false
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: 'logs'
      offline: false
      project: project
      log_model: false
      prefix: ''
  enable_checkpointing: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: 'checkpoints'
        filename: 'project-{epoch:02d}-{val_loss:.2f}'
        monitor: 'val/loss'
        mode: 'min'
        save_top_k: 1
        save_last: true
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: 'val/loss'
        mode: 'min'
        patience: 3
        min_delta: 0.001
  enable_progress_bar: true
  max_epochs: 200
  gradient_clip_val: 5
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  accelerator: auto
  strategy: auto 
  precision: 32
  benchmark: true
  num_nodes: 1